trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'newconnectionsaquib'
      repository: 'dccloudsaquibacr/my-app'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        latest
